darknet_ros_topic: /bounding_boxes
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
point_cloud_topic: /zed2/zed_node/point_cloud/cloud_registered
working_frame: zed2_left_camera_frame
mininum_detection_thereshold: 0.3
minimum_probability: 0.3
interested_classes: ["person", "car", "laptop"]
